///
/// @Generated by Mockolo
///



import UIKit


class ThumbnailServiceMock: ThumbnailService {
    init() { }


    private(set) var deleteThumbnailCallCount = 0
    var deleteThumbnailHandler: ((String) -> ())?
    func deleteThumbnail(localIdentifier: String) {
        deleteThumbnailCallCount += 1
        if let deleteThumbnailHandler = deleteThumbnailHandler {
            deleteThumbnailHandler(localIdentifier)
        }
        
    }

    private(set) var loadThumbnailCallCount = 0
    var loadThumbnailHandler: ((String) -> UIImage?)?
    func loadThumbnail(localIdentifier: String) -> UIImage? {
        loadThumbnailCallCount += 1
        if let loadThumbnailHandler = loadThumbnailHandler {
            return loadThumbnailHandler(localIdentifier)
        }
        return nil
    }
}

class PhotoServiceMock: PhotoService {
    init() { }


    private(set) var saveImageToPhotoLibraryCallCount = 0
    var saveImageToPhotoLibraryHandler: ((UIImage) async -> String?)?
    func saveImageToPhotoLibrary(_ image: UIImage) async -> String? {
        saveImageToPhotoLibraryCallCount += 1
        if let saveImageToPhotoLibraryHandler = saveImageToPhotoLibraryHandler {
            return await saveImageToPhotoLibraryHandler(image)
        }
        return nil
    }

    private(set) var loadPhotoAssetCallCount = 0
    var loadPhotoAssetHandler: ((String) async -> (image: UIImage, sha256Hash: String)?)?
    func loadPhotoAsset(localIdentifier: String) async -> (image: UIImage, sha256Hash: String)? {
        loadPhotoAssetCallCount += 1
        if let loadPhotoAssetHandler = loadPhotoAssetHandler {
            return await loadPhotoAssetHandler(localIdentifier)
        }
        return nil
    }
}



