///
/// @Generated by Mockolo
///



import Photos
import UIKit


class ThumbnailStoringMock: ThumbnailStoring {
    init() { }


    private(set) var saveThumbnailCallCount = 0
    var saveThumbnailHandler: ((String) async -> ())?
    func saveThumbnail(for localIdentifier: String) async {
        saveThumbnailCallCount += 1
        if let saveThumbnailHandler = saveThumbnailHandler {
            await saveThumbnailHandler(localIdentifier)
        }
        
    }

    private(set) var deleteThumbnailCallCount = 0
    var deleteThumbnailHandler: ((String) -> ())?
    func deleteThumbnail(localIdentifier: String) {
        deleteThumbnailCallCount += 1
        if let deleteThumbnailHandler = deleteThumbnailHandler {
            deleteThumbnailHandler(localIdentifier)
        }
        
    }

    private(set) var loadThumbnailCallCount = 0
    var loadThumbnailHandler: ((String) -> UIImage?)?
    func loadThumbnail(localIdentifier: String) -> UIImage? {
        loadThumbnailCallCount += 1
        if let loadThumbnailHandler = loadThumbnailHandler {
            return loadThumbnailHandler(localIdentifier)
        }
        return nil
    }
}



